### PR TITLE
Minor edits to text

### PR DESCRIPTION
**Pull request by amirmc**
Capitalised Pinata, added some emphasis and also a little more
context to the links to elsewhere.

### CODE REVIEW

**Comment by amirmc** [comment]
This was pretty good so I've not got many comments.  I'll write a short blog post over lunch and will post it live when the  site is due to be announced. Will have to take a screen grab of the image as unfortunately I can't use an SVG one.

**Comment by hannesm** [comment]
several test readers I asked were confused by `key` - it's first usage `private key of...` is clear, the next 3 should explicitly refer to `private key of the bitcoin address` (which is way too long)?
the last one should be `you can't have the private key of the CA`?

**Comment by amirmc** [comment]
Hmm, I'd managed to gloss over that in my first reading and yes, it is confusing.  There's nothing wrong with being more verbose if it's clearer (in this case it matters which key you're referring to)

**Comment by amirmc** [comment]
I think this sentence can do with a little more explanation, unless it's obvious to the security folks you're trying to target.

`It follows that it should be impossible to successfully establish a TLS connection as long as piñata is working properly`

**Pull request merged**
